import React, { Component } from 'react';
import { connect } from 'react-redux'
import Header from './components/Header'
import Game from './components/Game'
import { setupGame } from './actions/index'
import { MuiThemeProvider, createMuiTheme } from '@material-ui/core/styles'

const theme = createMuiTheme({
  typography: { fontFamily: "'Questrial', sans-serif", useNextVariants: true }
})

class App extends Component {
  componentDidMount() {
    this.props.setupGame(gameData, 16, 'Vulfpeck')
  }
  render() {
    return (
      <MuiThemeProvider theme={theme}>
        <div className="App">
          <Header />
          <Game />
        </div>
      </MuiThemeProvider>
    );
  }
}

const mapDispatchToProps = dispatch => ({
  setupGame: (gameData, size, title) => dispatch(setupGame(gameData, size, title))
})

export default connect(
  null,
  mapDispatchToProps
)(App)

const vulfGameData = {
  title: 'Vulfpeck',
  baseButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/images/vulf.png',
  correctButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/images/vulf_blue.png',
  playButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/images/vulfs.png',
  winningButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/images/vulf_red.png',
  setButton: 'https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/images/vulf_button.png',
  sounds : [
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Antwaun1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Antwaun2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Antwaun3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Antwaun4.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Antwaun5.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612FordFocus.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Intro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/1612Star.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/BackPocketFrogs.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/FunkyDuckAntwaunRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/adreinneBass.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/adreinneCall.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/adreinneResponse.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/adreinneRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/backPocketClarinet1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/backPocketClarinet2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/backPocketIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/backPocketOhYea.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/backPocketPutItIn.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/barbaraIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/barbaraTheme1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/barbaraTheme2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/beastlyBass1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/beastlyBass2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/beastlyTheme1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/beastlyTheme2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/beastlyTheme3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/birdwatcherIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/birdwatcherRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/birdwatcherRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cClubBassLick.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cClubBridge.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cClubChorus.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cClubDrumBreak.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cClubYes.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/carsTooCall.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/carsTooGuitar.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/carsTooResponse.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaBridge1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaCILA.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaDrumBreak.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaIntro2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaSingingRound.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaTheoJackson.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/cilaYuletideCheer.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/firstPlaceIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/firstPlaceRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/firstPlaceRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/fugueChorus.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/fugueCounterpoint.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/fugueIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier2Intro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier2Theme.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier3Intro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier3Riff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier3Riff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkier3Riff3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkierBass.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkierBreakDown.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkierTheme1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkierTheme2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkyDuckAntwaunIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkyDuckAntwaunRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkyDuckFunkyDuck.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/funkyDuckIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/gameWinnerBabyBabyBaby.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/gameWinnerBelieveInMe.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/gameWinnerGiveMeBall.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/gameWinnerLetItFly.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/kuhmilchRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/kuhmilchRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/meanGirlsIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/meanGirlsRiff.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/meanGirlsTheme.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medAcousticSounds.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medHahaRegion.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medInhale.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medRelease.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medTheseSensations.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medUnexaminedLife.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/medVulfIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/myFirstCarIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/myFirstCarRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/myFirstCarRiff3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/newsBeatRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/newsBeatRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/outroIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/outroRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/outroSax1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/outroSaxIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/promDrum.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/promIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/promTheme.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rango3GuitarRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rango3GuitarRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rango3GuitarRiff3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rango3Intro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rangoDrum.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rangoFill.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/rangoGroove.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/skyMallBass1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/skyMallBass2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/skyMallBass3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/skyMallBass4.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/skyMallIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileBubbles.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileRiff3.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/smileRiff4.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/sounds_audio_urls.csv",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/speedWalkerRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/speedwalkerRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/tomboyDrum.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/tomboyTheme.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentBass.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentLivingLoud.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentMoney.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentNiceCall.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentOutro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentProducts.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/waitMomentSoNice.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkRememberBass.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkRememberIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkRememberRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkRememberRiff2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkRememberSax.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkiesFootsteps.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkiesIntro.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkiesSynthRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/walkiesWoofWoof.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/welcomeBassRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/welcomeGuitarRiff1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/vulfpeck/sounds/welcomeSaxRiff1.wav"
  ]
}

const rmGameData = {
  title: 'Rick and Morty',
  baseButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/images/morty.png',
  correctButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/images/rick.png',
  playButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/images/rm.png',
  winningButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/images/meeseeks.png',
  setButton: 'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/images/portal.png',
  sounds:[ 
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/And_that\'s_the_way_news_goes.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Awww_Bitch.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Come_on_old_man.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Disqualified_version1.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Good_Job!.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Help!.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Hi_I\'m_mr_meeseeks_look_at_me.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/I\'m having a party, biiiiitch!.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/I\'m_ants_in_my_eye_johnson.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/I_like_what_you_got.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/In_bird_culture__this_is_considered.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Keep_Summer_Safe.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Oooo_yeah__caaan_doo!.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Praise_the_one_true_morty.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Riggity.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/Show_Me_What_U_got.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/That\'s_retarded.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/all_aboard.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/anatomy_park.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/annoyed_rick.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/baby_legs.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/backseat_parenting.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/butthole.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/cant_hide.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/dropping_loads.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/e4fd8935c4.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/for_real_times.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/get_schwifty_in_here.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/half_morty.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/hey_ya_you_doing_ok_.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/hit_the_sack_jack.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/i_love_morty.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/inside_ruben.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/intro.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/jealousy.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/let_me_go.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/let_me_out_.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/lick_my_balls.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/life.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/losing_him.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/monster.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/my_bad.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/my_man.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/oh_man.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/ohmygod.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/old_school_jews.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/outro.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/pi.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/rick.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/rick_is_a_dick.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/rubber_baby_baby_bunkers.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/stoked.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/thank_you.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/this_is_how_you_dream_bitch.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/too_tough.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/what_.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/woo_vu_luvub_dub_dub.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/yes_fuck_you_god_not_today_bitch.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/you_can\'t_go_out_there.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/you_dont_know_me.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/rick_and_morty/sounds/you_know_what_this_human_eats.wav' ]
}

const swGameData = {
  title: 'Star Wars',
  baseButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/star_wars/images/darth.png',
  correctButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/star_wars/images/chewy.png',
  playButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/star_wars/images/logo.png',
  winningButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/star_wars/images/yoda.png',
  setButton: 'https://s3.us-east-2.amazonaws.com/sound-game/star_wars/images/death_star.png',
  sounds: [
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Chewie-chatting.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Dont_get_cocky.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Dont_upset_a_wookie.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/I_have_you_now.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Lightsaber_ignites.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Obi_Wan_force_2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/Set_for_stun.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/alerted.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/as_u_wish.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/bad_feeling.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/blaster.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/blaster_good.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/chewy_roar.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/dark_side2_y.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/destiny.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/destroy_you.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/dont_like.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/dont_underestimate.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/expecting_you.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/fool.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/for_the_last_time.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/force.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/forcestrong.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/greetings_exalted.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/han_solo.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/help.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/honored.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/insignificant.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/jabba-the-hutt-laughing.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/jawa.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/lack_of_faith.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/laughfuzzball.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/learn.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/learn_the_ways.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/luke_never_turn.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/nerfherder.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/palpatine_hate.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/piece_o_junk.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/pointless.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-scream1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-squeaks1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-squeaks2.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-squeaks4.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-squeaks5.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/r2d2-whistle1.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/release_anger.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/servant.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/situation.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/stretch_out.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/switch-off.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/swluke01.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/swvader01.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/swvader02.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/swvader03.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/swvader04.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/taught_u_well.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/technological.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/the_force.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/vader_impressive.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/what.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/why_are_u_here_x.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/yoda-900Years.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/yoda-helpYou.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/yoda-strongAmI.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/yoda-thereIsNoTry.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/yodalaughing.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/your_father.wav",
    "https://s3.us-east-2.amazonaws.com/sound-game/star_wars/sounds/your_fault.wav"
  ]
}

const simpsonsGameData = {
  title: 'Simpsons',
  baseButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/images/bart.png',
  correctButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/images/lisa.png',
  playButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/images/couch.png',
  winningButtonImage: 'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/images/homer.png',
  setButton: 'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/images/donut.png',
  sounds: [ 
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Im-the-devil.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Mr-Burns-Blue-Blazes.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Mr-Burns-kiss-butt.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Mr-Burns-pish-posh.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Mr-Burns-punishment.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/Mr-Burns-sue-the-pants.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/balogna.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/beingay.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/boring.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/crap.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/damned.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/dancewgay.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/dearbaby.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/diddily-do-you-for.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/dillypickle.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/doh1.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/eum.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/fatkid.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/flute.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/fraid-so-infinity-plus-1.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/gramps.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/haha.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/hi-dily-hey.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/indeedily-doodily.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/kntbrockman_blam.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/krlaugh.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/krusty.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/lemealon.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/margenedpipe.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/mbeernut.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/mburger.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/mchocola.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/mcrumble.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/me-fail-English.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/moe_french.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/moehatefil.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ned_doodle.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/nudity.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ohsleep.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ralph_atecaps.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ralph_mittens.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ralphhurts.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/roger-doger.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/ruberpants.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/senseofhumor.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/stinky.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/toot.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/tvsucks.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/wig_inflate.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/wooky1.wav',
    'https://s3.us-east-2.amazonaws.com/sound-game/simpsons/sounds/xpaper.wav' ]
}

const gameData = [vulfGameData, rmGameData, swGameData, simpsonsGameData]